name: Manual Site Build

on:
  workflow_dispatch:
    inputs:
      build_env:
        description: 'Build environment (e.g., production, staging)'
        default: 'production'
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: File stuff
        run: cd web && ls

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: web
        run: npm install

      - name: Build project
        env:
          NODE_ENV: ${{ inputs.build_env }}
        working-directory: web
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (web/build)
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
